drop table if exists vehicle CASCADE;
drop table if exists vehicle_task CASCADE;
create table vehicle (id bigint generated by default as identity, colour varchar(255), horse_power integer not null, make varchar(255), model varchar(255), registration varchar(255), primary key (id));
create table vehicle_task (id bigint generated by default as identity, due_date date, name varchar(255), vehicle_id bigint, primary key (id));
alter table vehicle_task add constraint FKcvn9ad9fnccyrmayttu5eaap6 foreign key (vehicle_id) references vehicle;
