drop table if exists vehicle CASCADE;

create table vehicle (id bigint generated by default as identity, colour varchar(255), horse_power integer not null, make varchar(255), model varchar(255), registration varchar(255), primary key (id));